/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jlqanowbxgewhjwfsplz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpscWFub3dieGdld2hqd2ZzcGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMzg4ODksImV4cCI6MjA3NDYxNDg4OX0.q-L19nQsf7jWMu2N-1034xTLD6Tnwj3gJ3Rx5Bn1KZI"
